# Generated by Django 2.2.5 on 2021-02-03 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('user_birthday', models.DateTimeField(default=datetime.datetime(2021, 2, 3, 15, 53, 4, 351039, tzinfo=utc))),
                ('user_email', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_gu', models.CharField(max_length=50)),
                ('user_dong', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(max_length=12)),
            ],
        ),
    ]
