# Generated by Django 2.2.5 on 2021-02-03 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memregister',
            name='user_birthday',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 15, 53, 17, 577653, tzinfo=utc)),
        ),
    ]
