# Generated by Django 3.1.6 on 2021-02-03 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='memRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('user_birthday', models.DateTimeField(default=datetime.datetime(2021, 2, 3, 5, 34, 45, 584579, tzinfo=utc))),
                ('user_email', models.CharField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_gu', models.CharField(max_length=50)),
                ('user_dong', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='userRegister',
        ),
    ]
