# Generated by Django 3.1.6 on 2021-02-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayweather',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todayweather',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todayweather',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
