# Generated by Django 3.1.6 on 2021-02-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0002_auto_20210208_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayweather',
            name='sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todayweather',
            name='sunset',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
