# Generated by Django 3.1.6 on 2021-02-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210210_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='random', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.CharField(default='uncompleted', max_length=30),
        ),
    ]
