# Generated by Django 3.1.6 on 2021-02-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
                ('temp_high', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temp_low', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rain_prob', models.DecimalField(decimal_places=1, max_digits=3)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
    ]
