# Generated by Django 3.1.6 on 2021-02-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('address', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('writer', models.CharField(max_length=30)),
            ],
        ),
    ]
