# Generated by Django 3.1.6 on 2021-02-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='completed',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
